from typing import List, Optional

from pydantic import BaseModel, Field, ConfigDict


class ContextChunk(BaseModel):
    """
    Same field names/shape as m5.schemas.ContextChunk (and m3.schemas.ChunkResult
    before it) on purpose — this is a drop-in shape, not a hard import
    dependency on m5, so m6 can be tested/run/deployed independently.
    """

    model_config = ConfigDict(extra="ignore")

    chunk_id: str
    standard_number: Optional[str] = None
    section_title: Optional[str] = None
    section_number: Optional[str] = None
    content: str
    source_url: Optional[str] = None


class Citation(BaseModel):
    model_config = ConfigDict(extra="ignore")

    standard_number: Optional[str] = None
    section_title: Optional[str] = None
    section_number: Optional[str] = None
    source_url: Optional[str] = None


class UnverifiedCitation(BaseModel):
    """
    A standard number the generated answer text explicitly mentions, that
    does NOT correspond to any actually-retrieved chunk. This is the
    hallucination signal: the model citing a standard nobody ever gave it.
    """

    model_config = ConfigDict(extra="ignore")

    standard_number: str
    reason: str = "mentioned in the generated answer but not present in retrieved context"


class GroundAnswerRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")

    answer_text: str = Field(..., min_length=1, description="The raw text generated by the LLM (e.g. M5's output).")
    context_chunks: List[ContextChunk] = Field(
        default_factory=list, description="The chunks actually retrieved and given to the LLM as context."
    )
    citation_style: str = Field(
        default="footnote", description="How to render the citation block: footnote | inline | markdown_list"
    )


class GroundedAnswerResponse(BaseModel):
    model_config = ConfigDict(extra="ignore")

    answer_text: str = Field(..., description="The original, unmodified generated answer text.")
    formatted_answer: str = Field(..., description="answer_text with the citation block appended, ready to display.")
    citations: List[Citation] = Field(default_factory=list)
    unverified_citations: List[UnverifiedCitation] = Field(
        default_factory=list,
        description="Standard numbers the answer mentioned that weren't in the retrieved context — a hallucination flag.",
    )
    is_fully_grounded: bool = Field(
        ..., description="True only if at least one citation exists AND no unverified citations were found."
    )
