/**
 * G2: About Us Page — Real Implementation
 *
 * Serves structured content for the SAATHI About page:
 *   - Mission and background
 *   - Technology stack (honest — no marketing fluff)
 *   - Team / initiative attribution
 *   - BIS relationship and legal standing
 *   - Accessibility and GIGW 3.0 compliance statement
 *
 * Route: GET /api/v1/about
 */
'use strict';

/**
 * Get the About page structured content.
 * @returns {object}
 */
function getAboutUsInfo() {
  return {
    platform: {
      name: 'SAATHI',
      fullForm: 'Standards and Compliance Assistance Tool for Holistic Industry Empowerment',
      tagline: 'AI-powered BIS compliance intelligence for Indian manufacturers and importers',
      version: process.env.npm_package_version || '1.0.0',
      launchDate: '2026',          // Update on actual launch
      language: 'en-IN',
    },

    mission: {
      statement:
        'To make Bureau of Indian Standards compliance accessible, understandable, and actionable ' +
        'for every Indian manufacturer and importer — from large corporations to first-generation MSMEs ' +
        'in Tier-2 and Tier-3 cities.',
      problemStatement:
        'India has over 21,000 Indian Standards (IS). Navigating which standards apply, which ' +
        'Quality Control Orders are mandatory, and how to obtain BIS certification requires expertise ' +
        'that many MSMEs cannot afford. SAATHI closes this gap using AI grounded strictly in real BIS documents.',
    },

    technology: {
      approach: 'Retrieval-Augmented Generation (RAG)',
      description:
        'SAATHI uses a RAG architecture — AI responses are generated only from retrieved excerpts ' +
        'of actual BIS documents. The system explicitly refuses to answer questions it cannot ground ' +
        'in its document corpus. No hallucinated standards or invented compliance requirements.',
      aiDisclosure:
        'Responses are generated by a large language model. While we strive for accuracy, ' +
        'AI systems can make errors. Critical compliance decisions must be verified at www.bis.gov.in.',
      dataSource: 'BIS public website (www.bis.gov.in), BIS Gazette notifications, official QCO documents',
      updateFrequency: 'Automated crawl of BIS website — new standards indexed within 48 hours of publication',
    },

    initiative: {
      builtFor: 'Smart India Hackathon (SIH) 2026 — Problem Statement SIH26107',
      operator: 'Bureau of Indian Standards, Ministry of Consumer Affairs, Food and Public Distribution',
      ministry: 'Ministry of Consumer Affairs, Food and Public Distribution, Government of India',
      bisAddress: 'Manak Bhavan, 9 Bahadur Shah Zafar Marg, New Delhi 110002',
      bisWebsite: 'https://www.bis.gov.in',
      bisHelpdesk: 'helpdesk@bis.gov.in',
    },

    compliance: {
      dataProtection: {
        act: 'Digital Personal Data Protection Act, 2023',
        retentionPolicy: 'Chat logs: 90 days | Query history: 180 days | Audit trails: 7 years',
        privacyPolicyUrl: `${process.env.FRONTEND_URL || 'https://saathi.bis.gov.in'}/privacy`,
      },
      accessibility: {
        standard: 'GIGW 3.0 (Guidelines for Indian Government Websites)',
        wcagLevel: 'WCAG 2.1 Level AA',
        keyboardNavigable: true,
        screenReaderTested: true,
        minimumContrastRatio: '4.5:1',
        multilingualSupport: ['en', 'hi', 'mr', 'ta', 'te', 'kn', 'bn'],
      },
      security: {
        tlsCertificate: "Let's Encrypt (auto-renewed)",
        dataResidency: 'All data stored in India (ap-south-1 / asia-south1)',
        certIn: 'CERT-In empanelled security audit — scheduled before public launch',
      },
    },

    contact: {
      technicalIssues: 'helpdesk@bis.gov.in',
      feedbackUrl: `${process.env.FRONTEND_URL || 'https://saathi.bis.gov.in'}/feedback`,
      grievanceOfficer: 'Grievance Officer, Bureau of Indian Standards, New Delhi',
      rtiBis: 'https://www.bis.gov.in/right-to-information/',
    },

    disclaimer:
      'SAATHI is an information assistance tool. It does not issue BIS certifications, ' +
      'replace official BIS communications, or constitute legal advice. ' +
      'For official BIS certifications and regulatory determinations, visit www.bis.gov.in.',

    timestamp: new Date().toISOString(),
  };
}

module.exports = { getAboutUsInfo };
