import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { Loader2, Paperclip, Send, X } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Navigate } from "@/lib/router-compat";

import { AmbientBackground } from "@/components/ambient-background";
import { staggerTransition } from "@/lib/motion";
import { Chat3DBackground } from "@/components/chat-3d-background";
import { useUserProfile } from "@/lib/profile";
import { AppSidebar } from "@/components/app-sidebar";
import { BrandMark } from "@/components/brand-mark";
import { ChatBubble } from "@/components/chat-bubble";
import { MobileSidebar } from "@/components/mobile-sidebar";
import { ProductClassificationWizard } from "@/components/product-classification-wizard";
import { SuccessCheck } from "@/components/success-check";
import { ThinkingIndicator } from "@/components/thinking-indicator";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { getMockBotReply, getMockReplyForCategory } from "@/lib/mock-bot";
import { useRole } from "@/lib/role";
import {
  useConversationHistory,
  type StoredConversation,
} from "@/hooks/use-conversation-history";
import type { ChatMessage, MessageFeedback } from "@/lib/types";
import { useThemeShortcut } from "@/hooks/use-theme-shortcut";

// Send button feedback: a short spinner, then the shared SuccessCheck, then
// back to the send icon.
const SEND_STATUS_SENDING_MS = 350;
const SEND_STATUS_SENT_MS = 700;
type SendStatus = "idle" | "sending" | "sent";

const MOCK_REPLY_DELAY_MS = 500;

function makeConversationId(): string {
  return typeof crypto !== "undefined" && crypto.randomUUID
    ? crypto.randomUUID()
    : `${Date.now()}`;
}

// A sent user question is real free text (nothing to re-translate it with),
// but a mock bot reply is demo content — store which canned reply it is and
// resolve its text/citations from the current language on every render.
// "resolved" is a frozen message loaded back from a past saved conversation
// (see handleSelectConversation) — it renders as-is, with no re-translation
// or reply-completion wiring, since it already finished "typing" long ago.
type SentEntry =
  | { kind: "user"; text: string }
  | { kind: "mockReply"; replyIndex: number }
  | { kind: "categoryReply"; categoryKey: string }
  | { kind: "resolved"; message: ChatMessage };

// A queued message is either a free-typed question (round-robin mock reply)
// or one generated by the classification wizard, which carries the chosen
// category so its reply matches that category's seed standard instead.
interface QueuedMessage {
  text: string;
  categoryKey?: string;
}

function App() {
  useThemeShortcut();
  const { t, i18n } = useTranslation(["chat", "conversation"]);
  const { role, ready } = useRole();

  const history = useConversationHistory();
  const [sentEntries, setSentEntries] = useState<SentEntry[]>([]);
  const messages: ChatMessage[] = sentEntries.map((entry) => {
    if (entry.kind === "user") return { sender: "user", text: entry.text };
    if (entry.kind === "resolved") return entry.message;
    if (entry.kind === "categoryReply") {
      return {
        sender: "bot",
        ...getMockReplyForCategory(entry.categoryKey, i18n.language),
      };
    }
    return getMockBotReply(entry.replyIndex, i18n.language);
  });
  const rawSuggested = t("chat:starterPrompts", {
    returnObjects: true,
  });
  const suggestedQuestions = (Array.isArray(rawSuggested) ? rawSuggested : []) as string[];
  const prefersReducedMotion = useReducedMotion();

  const [input, setInput] = useState("");
  const [attachedFileName, setAttachedFileName] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  // D7 — feedback keyed by the same `message-${index}` id used for
  // scroll, so it can later be joined with analytics data.
  const [feedbackByMessageId, setFeedbackByMessageId] = useState<
    Record<string, MessageFeedback>
  >({});
  const contentRef = useRef<HTMLDivElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);
  const mockReplyCountRef = useRef(0);
  const pendingReplyTimeoutRef = useRef<number | undefined>(undefined);
  const [sendStatus, setSendStatus] = useState<SendStatus>("idle");
  const sendStatusTimeoutRef = useRef<number | undefined>(undefined);
  useEffect(() => () => window.clearTimeout(sendStatusTimeoutRef.current), []);

  // While a bot reply is still being typed out, any further sent messages
  // wait in queueRef (isProcessingRef guards it) rather than being shown
  // immediately, so the conversation stays in strict alternating order.
  const queueRef = useRef<QueuedMessage[]>([]);
  const isProcessingRef = useRef(false);
  const [isAwaitingReply, setIsAwaitingReply] = useState(false);
  const { profile: userProfile, setProfile: setUserProfile } = useUserProfile();

  // Auto-saves the active thread to history as it grows — there's no
  // separate "save" action, since a discarded thread is just one nothing
  // was ever typed into (saveConversation no-ops on an empty message list).
  useEffect(() => {
    if (!history.ready || sentEntries.length === 0) return;
    history.saveConversation(history.activeId, messages);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sentEntries, history.ready, history.activeId, i18n.language]);

  const pendingReplyMessageIndex =
    isAwaitingReply &&
    sentEntries.length > 0 &&
    sentEntries[sentEntries.length - 1].kind !== "user"
      ? sentEntries.length - 1
      : null;

  // The reply hasn't been appended to sentEntries yet (still inside the
  // MOCK_REPLY_DELAY_MS timeout) — show a placeholder bubble until it lands
  // and its own typing animation takes over.
  const isThinking =
    isAwaitingReply &&
    (sentEntries.length === 0 ||
      sentEntries[sentEntries.length - 1].kind === "user");

  useEffect(() => {
    const content = contentRef.current;
    if (!content) return;

    const observer = new ResizeObserver(() => {
      // Nothing to follow yet: on short screens the empty state overflows,
      // and scrolling to its end would hide the hero above the fold.
      if (!content.querySelector('[id^="message-"]')) return;
      bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
    });
    observer.observe(content);

    return () => observer.disconnect();
  }, []);

  // Shows the next queued message (if any) and schedules its reply, unless
  // a reply is already in flight — handleReplyRevealed() calls this again
  // once that reply finishes typing, advancing the queue one turn at a time.
  function processNext() {
    if (isProcessingRef.current) return;
    const next = queueRef.current.shift();
    if (next === undefined) return;

    isProcessingRef.current = true;
    setIsAwaitingReply(true);
    setSentEntries((prev) => [...prev, { kind: "user", text: next.text }]);

    // MOCK: swap this timeout + canned reply for a real backend/API call
    // (e.g. POST the question, stream the answer via SSE) once it exists.
    const replyEntry: SentEntry = next.categoryKey
      ? { kind: "categoryReply", categoryKey: next.categoryKey }
      : { kind: "mockReply", replyIndex: mockReplyCountRef.current++ };
    window.clearTimeout(pendingReplyTimeoutRef.current);
    pendingReplyTimeoutRef.current = window.setTimeout(() => {
      setSentEntries((prev) => [...prev, replyEntry]);
    }, MOCK_REPLY_DELAY_MS);
  }

  function handleReplyRevealed() {
    isProcessingRef.current = false;
    setIsAwaitingReply(false);
    processNext();
  }

  // Stops any in-flight reply and resets the live queue — shared by
  // "New chat", switching to a saved conversation, and deleting the one
  // that's currently open, since all three replace what's on screen.
  function resetLiveThread() {
    window.clearTimeout(pendingReplyTimeoutRef.current);
    window.clearTimeout(sendStatusTimeoutRef.current);
    setSendStatus("idle");
    queueRef.current = [];
    isProcessingRef.current = false;
    setIsAwaitingReply(false);
    setFeedbackByMessageId({});
  }

  function handleNewChat() {
    resetLiveThread();
    setSentEntries([]);
    history.setActiveId(makeConversationId());
  }

  function handleSelectConversation(conversation: StoredConversation) {
    resetLiveThread();
    setSentEntries(
      conversation.messages.map((message) => ({ kind: "resolved", message })),
    );
    history.setActiveId(conversation.id);
  }

  function handleDeleteConversation(id: string) {
    history.deleteConversation(id);
    if (id === history.activeId) handleNewChat();
  }

  // Purely cosmetic: handleSend is synchronous (mock replies, no network
  // round trip), so this gives the send button a visible landing instead
  // of an instant icon swap. A real backend would drive "sending" from the
  // request lifecycle instead.
  function runSendStatusSequence() {
    window.clearTimeout(sendStatusTimeoutRef.current);
    setSendStatus("sending");
    sendStatusTimeoutRef.current = window.setTimeout(() => {
      setSendStatus("sent");
      sendStatusTimeoutRef.current = window.setTimeout(() => {
        setSendStatus("idle");
      }, SEND_STATUS_SENT_MS);
    }, SEND_STATUS_SENDING_MS);
  }

  function handleSend() {
    if (input.trim() === "" && !attachedFileName) return;
    const attachmentSuffix = attachedFileName
      ? ` [Image attached: ${attachedFileName}]`
      : "";
    queueRef.current.push({
      text: `${input.trim()}${attachmentSuffix}`.trim(),
    });
    setInput("");
    setAttachedFileName(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
    runSendStatusSequence();
    processNext();
  }

  function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith("image/")) return;
    setAttachedFileName(file.name);
  }

  function handleWizardSubmit(question: string, categoryKey: string) {
    queueRef.current.push({ text: question, categoryKey });
    processNext();
  }

  function handleFeedbackChange(
    messageId: string,
    feedback: MessageFeedback | undefined,
  ) {
    setFeedbackByMessageId((prev) => {
      if (feedback === undefined) {
        const next = { ...prev };
        delete next[messageId];
        return next;
      }
      return { ...prev, [messageId]: feedback };
    });
  }

  // No role set means no one has logged in — send them to the landing
  // page's login flow instead of showing chat.
  if (!ready) return null;

  if (!role) {
    return <Navigate to="/" replace />;
  }

  return (
    <div className="relative h-[calc(100dvh-3.5rem)] w-full overflow-hidden bg-background">
      <AmbientBackground />
      <div className="relative z-10 flex h-full w-full">
        <AppSidebar
          conversations={history.conversations}
          activeConversationId={history.activeId}
          onSelectConversation={handleSelectConversation}
          onDeleteConversation={handleDeleteConversation}
          onNewChat={handleNewChat}
          profile={userProfile}
          onProfileChange={setUserProfile}
        />

        <div className="flex min-w-0 flex-1 justify-center px-0 sm:px-4">
          <div className="flex h-full w-full max-w-2xl flex-col">
            <header className="relative z-10 flex items-center gap-2 border-b border-border px-4 py-1.5 sm:px-6 md:hidden">
              <MobileSidebar
                conversations={history.conversations}
                activeConversationId={history.activeId}
                onSelectConversation={handleSelectConversation}
                onDeleteConversation={handleDeleteConversation}
                onNewChat={handleNewChat}
                profile={userProfile}
                onProfileChange={setUserProfile}
              />
            </header>

            <ScrollArea className="min-w-0 flex-1 min-h-0">
              <div
                ref={contentRef}
                className="flex min-h-full min-w-0 flex-col gap-3 p-4 sm:p-6"
              >
                {messages.length === 0 && !isThinking && (
                  <motion.div
                    initial={
                      prefersReducedMotion ? false : { opacity: 0, y: 10 }
                    }
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    className="flex min-h-[22rem] flex-1 flex-col items-center justify-center px-2 py-8 text-center sm:px-6"
                  >
                    <motion.div
                      className="mb-4"
                      animate={
                        prefersReducedMotion
                          ? undefined
                          : { scale: [1, 1.04, 1] }
                      }
                      transition={
                        prefersReducedMotion
                          ? undefined
                          : { duration: 3, repeat: Infinity, ease: "easeInOut" }
                      }
                    >
                      <BrandMark
                        size="sm"
                        punchDot={false}
                        className="rounded-xl shadow-[inset_0_1px_0_rgba(255,255,255,0.35),0_10px_18px_rgba(12,50,86,0.14)]"
                      />
                    </motion.div>
                    <h1 className="font-sans text-2xl font-semibold tracking-tight text-primary">
                      {t("chat:clearChat.emptyTitle")}
                    </h1>
                    <p className="mt-2 max-w-xs text-sm leading-relaxed text-muted-foreground">
                      {t("chat:clearChat.emptyDescription")}
                    </p>
                    {suggestedQuestions.length > 0 && (
                      <div className="mt-5 flex w-full max-w-md flex-col gap-2">
                        {suggestedQuestions.map((question, index) => (
                          <motion.button
                            key={question}
                            type="button"
                            initial={
                              prefersReducedMotion
                                ? false
                                : { opacity: 0, y: 12 }
                            }
                            animate={{ opacity: 1, y: 0 }}
                            // Reveal's spring (ENTRANCE_TRANSITION) and its
                            // 0.08s stagger step, starting as the heading
                            // settles.
                            transition={staggerTransition(index + 2)}
                            onClick={() => setInput(question)}
                            className="flex min-h-14 w-full items-center rounded-md border border-border bg-card px-3.5 py-2.5 text-start text-xs leading-snug font-normal text-foreground sm:min-h-0 transition-colors hover:border-primary/40 hover:bg-secondary hover:text-secondary-foreground"
                          >
                            {question}
                          </motion.button>
                        ))}
                      </div>
                    )}
                  </motion.div>
                )}
                {messages.map((msg, index) => (
                  <ChatBubble
                    key={index}
                    id={`message-${index}`}
                    message={msg}
                    onRevealComplete={
                      index === pendingReplyMessageIndex
                        ? handleReplyRevealed
                        : undefined
                    }
                    feedback={feedbackByMessageId[`message-${index}`]}
                    onFeedbackChange={(feedback) =>
                      handleFeedbackChange(`message-${index}`, feedback)
                    }
                  />
                ))}
                <AnimatePresence>
                  {isThinking && <ThinkingIndicator />}
                </AnimatePresence>
                <div ref={bottomRef} />
              </div>
            </ScrollArea>

            <div className="relative flex flex-col gap-1.5 px-4 pt-2 pb-3 before:pointer-events-none before:absolute before:inset-x-0 before:-top-6 before:h-6 before:bg-gradient-to-t before:from-background before:to-transparent sm:px-6 sm:pb-4">
              <ProductClassificationWizard onSubmit={handleWizardSubmit} />
              <AnimatePresence>
                {attachedFileName && (
                  <motion.div
                    initial={
                      prefersReducedMotion ? false : { opacity: 0, scale: 0.92 }
                    }
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.92 }}
                    transition={{ duration: 0.2 }}
                    className="flex items-center gap-2 self-start rounded-md border border-primary/20 bg-primary/8 px-3 py-1.5 text-xs text-primary"
                  >
                    <Paperclip className="size-3.5" aria-hidden />
                    <span className="max-w-[220px] truncate">
                      {attachedFileName}
                    </span>
                    <button
                      type="button"
                      onClick={() => {
                        setAttachedFileName(null);
                        if (fileInputRef.current)
                          fileInputRef.current.value = "";
                      }}
                      className="rounded-full p-0.5 transition-[background-color,transform] duration-150 hover:scale-110 hover:bg-primary/10 active:scale-95"
                      aria-label="Remove attached image"
                    >
                      <X className="size-3" aria-hidden />
                    </button>
                  </motion.div>
                )}
              </AnimatePresence>
              <div className="flex w-full items-center gap-1.5 rounded-md border border-input bg-card p-1.5 shadow-[var(--shadow-elevation-1)] transition-[border-color,box-shadow] duration-200 focus-within:border-primary focus-within:ring-3 focus-within:ring-ring/20">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={handleFileChange}
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => fileInputRef.current?.click()}
                  className="size-10 shrink-0 rounded-sm text-muted-foreground hover:bg-muted hover:text-foreground"
                  aria-label="Attach an image"
                >
                  <Paperclip className="size-4" aria-hidden />
                </Button>
                <Input
                  type="text"
                  placeholder={t("chat:inputPlaceholder")}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      handleSend();
                    }
                  }}
                  className="h-10 flex-1 border-0 bg-transparent px-2 text-foreground shadow-none placeholder:text-muted-foreground focus-visible:shadow-none focus-visible:ring-0 focus-visible:ring-offset-0 dark:bg-transparent"
                />
                <Button
                  onClick={handleSend}
                  size="icon"
                  disabled={
                    sendStatus !== "idle" ||
                    (input.trim() === "" && !attachedFileName)
                  }
                  className="group size-10 shrink-0 rounded-sm bg-primary text-primary-foreground transition-colors duration-200 enabled:hover:bg-primary/90 disabled:opacity-50"
                  aria-label={t("chat:sendAriaLabel")}
                >
                  <AnimatePresence mode="wait" initial={false}>
                    {sendStatus === "sending" ? (
                      <motion.span
                        key="sending"
                        initial={
                          prefersReducedMotion
                            ? false
                            : { opacity: 0, scale: 0.8 }
                        }
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.8 }}
                        transition={{ duration: 0.15 }}
                        className="flex items-center justify-center"
                      >
                        <Loader2 className="size-4 animate-spin" aria-hidden />
                      </motion.span>
                    ) : sendStatus === "sent" ? (
                      <motion.span
                        key="sent"
                        initial={
                          prefersReducedMotion
                            ? false
                            : { opacity: 0, scale: 0.8 }
                        }
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.8 }}
                        transition={{ duration: 0.15 }}
                        className="flex items-center justify-center"
                      >
                        <SuccessCheck
                          size="sm"
                          className="size-4 text-primary-foreground"
                        />
                      </motion.span>
                    ) : (
                      <motion.span
                        key="idle"
                        initial={
                          prefersReducedMotion
                            ? false
                            : { opacity: 0, scale: 0.8 }
                        }
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.8 }}
                        transition={{ duration: 0.15 }}
                        className="flex items-center justify-center"
                      >
                        <Send className="size-4 transition-transform duration-200 group-enabled:group-hover:translate-x-0.5 group-enabled:group-hover:-translate-y-0.5" />
                      </motion.span>
                    )}
                  </AnimatePresence>
                </Button>
              </div>
              <p className="text-center text-2xs text-muted-foreground">
                {t("chat:inputDisclaimer")}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
