/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as BusinessAccountRouteImport } from './routes/business-account'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClassificationRouteImport } from './routes/classification'
import { Route as ComplianceChainRouteImport } from './routes/compliance-chain'
import { Route as ConformityRouteImport } from './routes/conformity'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocumentCorrectionsRouteImport } from './routes/document-corrections'
import { Route as DocumentCortexRouteImport } from './routes/document-cortex'
import { Route as FactoryAuditsRouteImport } from './routes/factory-audits'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as IntelFeedRouteImport } from './routes/intel-feed'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as JurisdictionRouteImport } from './routes/jurisdiction'
import { Route as KnowledgeNexusRouteImport } from './routes/knowledge-nexus'
import { Route as LaboratoryMatcherRouteImport } from './routes/laboratory-matcher'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LicenseActionsRouteImport } from './routes/license-actions'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfficerVisitsRouteImport } from './routes/officer-visits'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecallsRouteImport } from './routes/recalls'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegulatoryAlertsRouteImport } from './routes/regulatory-alerts'
import { Route as RegulatoryRadarRouteImport } from './routes/regulatory-radar'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as SampleTrackerRouteImport } from './routes/sample-tracker'
import { Route as SchemeSelectorRouteImport } from './routes/scheme-selector'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminRetrievalQualityRouteImport } from './routes/admin.retrieval-quality'
import { Route as PaymentsApplicationIdRouteImport } from './routes/payments.$applicationId'
import { Route as RegistrationNewRouteImport } from './routes/registration.new'
import { Route as RenewalsIndexRouteImport } from './routes/renewals.index'
import { Route as StandardsIndexRouteImport } from './routes/standards.index'
import { Route as StandardsStandardKeyRouteImport } from './routes/standards_.$standardKey'
import { Route as VerifyCertificateRouteImport } from './routes/verify.certificate'
import { Route as RenewalsApplicationIdIndexRouteImport } from './routes/renewals.$applicationId.index'
import { Route as RenewalsApplicationIdWizardRouteImport } from './routes/renewals.$applicationId.wizard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAccountRoute = BusinessAccountRouteImport.update({
  id: '/business-account',
  path: '/business-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationRoute = ClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceChainRoute = ComplianceChainRouteImport.update({
  id: '/compliance-chain',
  path: '/compliance-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformityRoute = ConformityRouteImport.update({
  id: '/conformity',
  path: '/conformity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentCorrectionsRoute = DocumentCorrectionsRouteImport.update({
  id: '/document-corrections',
  path: '/document-corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentCortexRoute = DocumentCortexRouteImport.update({
  id: '/document-cortex',
  path: '/document-cortex',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryAuditsRoute = FactoryAuditsRouteImport.update({
  id: '/factory-audits',
  path: '/factory-audits',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelFeedRoute = IntelFeedRouteImport.update({
  id: '/intel-feed',
  path: '/intel-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const JurisdictionRoute = JurisdictionRouteImport.update({
  id: '/jurisdiction',
  path: '/jurisdiction',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeNexusRoute = KnowledgeNexusRouteImport.update({
  id: '/knowledge-nexus',
  path: '/knowledge-nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryMatcherRoute = LaboratoryMatcherRouteImport.update({
  id: '/laboratory-matcher',
  path: '/laboratory-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseActionsRoute = LicenseActionsRouteImport.update({
  id: '/license-actions',
  path: '/license-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerVisitsRoute = OfficerVisitsRouteImport.update({
  id: '/officer-visits',
  path: '/officer-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallsRoute = RecallsRouteImport.update({
  id: '/recalls',
  path: '/recalls',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryAlertsRoute = RegulatoryAlertsRouteImport.update({
  id: '/regulatory-alerts',
  path: '/regulatory-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryRadarRoute = RegulatoryRadarRouteImport.update({
  id: '/regulatory-radar',
  path: '/regulatory-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleTrackerRoute = SampleTrackerRouteImport.update({
  id: '/sample-tracker',
  path: '/sample-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemeSelectorRoute = SchemeSelectorRouteImport.update({
  id: '/scheme-selector',
  path: '/scheme-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetrievalQualityRoute = AdminRetrievalQualityRouteImport.update({
  id: '/admin/retrieval-quality',
  path: '/admin/retrieval-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsApplicationIdRoute = PaymentsApplicationIdRouteImport.update({
  id: '/payments/$applicationId',
  path: '/payments/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationNewRoute = RegistrationNewRouteImport.update({
  id: '/registration/new',
  path: '/registration/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsIndexRoute = RenewalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RenewalsRoute,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandardsRoute,
} as any)
const StandardsStandardKeyRoute = StandardsStandardKeyRouteImport.update({
  id: '/standards_/$standardKey',
  path: '/standards/$standardKey',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify/certificate',
  path: '/verify/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsApplicationIdIndexRoute =
  RenewalsApplicationIdIndexRouteImport.update({
    id: '/$applicationId/',
    path: '/$applicationId/',
    getParentRoute: () => RenewalsRoute,
  } as any)
const RenewalsApplicationIdWizardRoute =
  RenewalsApplicationIdWizardRouteImport.update({
    id: '/$applicationId/wizard',
    path: '/$applicationId/wizard',
    getParentRoute: () => RenewalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/business-account': typeof BusinessAccountRoute
  '/calendar': typeof CalendarRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/classification': typeof ClassificationRoute
  '/compliance-chain': typeof ComplianceChainRoute
  '/conformity': typeof ConformityRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/document-corrections': typeof DocumentCorrectionsRoute
  '/document-cortex': typeof DocumentCortexRoute
  '/factory-audits': typeof FactoryAuditsRoute
  '/grievance': typeof GrievanceRoute
  '/intel-feed': typeof IntelFeedRoute
  '/invoices': typeof InvoicesRoute
  '/jurisdiction': typeof JurisdictionRoute
  '/knowledge-nexus': typeof KnowledgeNexusRoute
  '/laboratory-matcher': typeof LaboratoryMatcherRoute
  '/legal': typeof LegalRoute
  '/license-actions': typeof LicenseActionsRoute
  '/locations': typeof LocationsRoute
  '/notifications': typeof NotificationsRoute
  '/officer-visits': typeof OfficerVisitsRoute
  '/profile': typeof ProfileRoute
  '/recalls': typeof RecallsRoute
  '/register': typeof RegisterRoute
  '/regulatory-alerts': typeof RegulatoryAlertsRoute
  '/regulatory-radar': typeof RegulatoryRadarRoute
  '/renewals': typeof RenewalsRouteWithChildren
  '/sample-tracker': typeof SampleTrackerRoute
  '/scheme-selector': typeof SchemeSelectorRoute
  '/standards': typeof StandardsRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/retrieval-quality': typeof AdminRetrievalQualityRoute
  '/payments/$applicationId': typeof PaymentsApplicationIdRoute
  '/registration/new': typeof RegistrationNewRoute
  '/standards/$standardKey': typeof StandardsStandardKeyRoute
  '/verify/certificate': typeof VerifyCertificateRoute
  '/admin/': typeof AdminIndexRoute
  '/renewals/': typeof RenewalsIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/renewals/$applicationId/wizard': typeof RenewalsApplicationIdWizardRoute
  '/renewals/$applicationId/': typeof RenewalsApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/business-account': typeof BusinessAccountRoute
  '/calendar': typeof CalendarRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/classification': typeof ClassificationRoute
  '/compliance-chain': typeof ComplianceChainRoute
  '/conformity': typeof ConformityRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/document-corrections': typeof DocumentCorrectionsRoute
  '/document-cortex': typeof DocumentCortexRoute
  '/factory-audits': typeof FactoryAuditsRoute
  '/grievance': typeof GrievanceRoute
  '/intel-feed': typeof IntelFeedRoute
  '/invoices': typeof InvoicesRoute
  '/jurisdiction': typeof JurisdictionRoute
  '/knowledge-nexus': typeof KnowledgeNexusRoute
  '/laboratory-matcher': typeof LaboratoryMatcherRoute
  '/legal': typeof LegalRoute
  '/license-actions': typeof LicenseActionsRoute
  '/locations': typeof LocationsRoute
  '/notifications': typeof NotificationsRoute
  '/officer-visits': typeof OfficerVisitsRoute
  '/profile': typeof ProfileRoute
  '/recalls': typeof RecallsRoute
  '/register': typeof RegisterRoute
  '/regulatory-alerts': typeof RegulatoryAlertsRoute
  '/regulatory-radar': typeof RegulatoryRadarRoute
  '/sample-tracker': typeof SampleTrackerRoute
  '/scheme-selector': typeof SchemeSelectorRoute
  '/vault': typeof VaultRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/retrieval-quality': typeof AdminRetrievalQualityRoute
  '/payments/$applicationId': typeof PaymentsApplicationIdRoute
  '/registration/new': typeof RegistrationNewRoute
  '/standards/$standardKey': typeof StandardsStandardKeyRoute
  '/verify/certificate': typeof VerifyCertificateRoute
  '/admin': typeof AdminIndexRoute
  '/renewals': typeof RenewalsIndexRoute
  '/standards': typeof StandardsIndexRoute
  '/renewals/$applicationId/wizard': typeof RenewalsApplicationIdWizardRoute
  '/renewals/$applicationId': typeof RenewalsApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/business-account': typeof BusinessAccountRoute
  '/calendar': typeof CalendarRoute
  '/certificates': typeof CertificatesRoute
  '/chat': typeof ChatRoute
  '/classification': typeof ClassificationRoute
  '/compliance-chain': typeof ComplianceChainRoute
  '/conformity': typeof ConformityRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/document-corrections': typeof DocumentCorrectionsRoute
  '/document-cortex': typeof DocumentCortexRoute
  '/factory-audits': typeof FactoryAuditsRoute
  '/grievance': typeof GrievanceRoute
  '/intel-feed': typeof IntelFeedRoute
  '/invoices': typeof InvoicesRoute
  '/jurisdiction': typeof JurisdictionRoute
  '/knowledge-nexus': typeof KnowledgeNexusRoute
  '/laboratory-matcher': typeof LaboratoryMatcherRoute
  '/legal': typeof LegalRoute
  '/license-actions': typeof LicenseActionsRoute
  '/locations': typeof LocationsRoute
  '/notifications': typeof NotificationsRoute
  '/officer-visits': typeof OfficerVisitsRoute
  '/profile': typeof ProfileRoute
  '/recalls': typeof RecallsRoute
  '/register': typeof RegisterRoute
  '/regulatory-alerts': typeof RegulatoryAlertsRoute
  '/regulatory-radar': typeof RegulatoryRadarRoute
  '/renewals': typeof RenewalsRouteWithChildren
  '/sample-tracker': typeof SampleTrackerRoute
  '/scheme-selector': typeof SchemeSelectorRoute
  '/standards': typeof StandardsRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/retrieval-quality': typeof AdminRetrievalQualityRoute
  '/payments/$applicationId': typeof PaymentsApplicationIdRoute
  '/registration/new': typeof RegistrationNewRoute
  '/standards_/$standardKey': typeof StandardsStandardKeyRoute
  '/verify/certificate': typeof VerifyCertificateRoute
  '/admin/': typeof AdminIndexRoute
  '/renewals/': typeof RenewalsIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/renewals/$applicationId/wizard': typeof RenewalsApplicationIdWizardRoute
  '/renewals/$applicationId/': typeof RenewalsApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeals'
    | '/business-account'
    | '/calendar'
    | '/certificates'
    | '/chat'
    | '/classification'
    | '/compliance-chain'
    | '/conformity'
    | '/dashboard'
    | '/developers'
    | '/document-corrections'
    | '/document-cortex'
    | '/factory-audits'
    | '/grievance'
    | '/intel-feed'
    | '/invoices'
    | '/jurisdiction'
    | '/knowledge-nexus'
    | '/laboratory-matcher'
    | '/legal'
    | '/license-actions'
    | '/locations'
    | '/notifications'
    | '/officer-visits'
    | '/profile'
    | '/recalls'
    | '/register'
    | '/regulatory-alerts'
    | '/regulatory-radar'
    | '/renewals'
    | '/sample-tracker'
    | '/scheme-selector'
    | '/standards'
    | '/vault'
    | '/admin/documents'
    | '/admin/retrieval-quality'
    | '/payments/$applicationId'
    | '/registration/new'
    | '/standards/$standardKey'
    | '/verify/certificate'
    | '/admin/'
    | '/renewals/'
    | '/standards/'
    | '/renewals/$applicationId/wizard'
    | '/renewals/$applicationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeals'
    | '/business-account'
    | '/calendar'
    | '/certificates'
    | '/chat'
    | '/classification'
    | '/compliance-chain'
    | '/conformity'
    | '/dashboard'
    | '/developers'
    | '/document-corrections'
    | '/document-cortex'
    | '/factory-audits'
    | '/grievance'
    | '/intel-feed'
    | '/invoices'
    | '/jurisdiction'
    | '/knowledge-nexus'
    | '/laboratory-matcher'
    | '/legal'
    | '/license-actions'
    | '/locations'
    | '/notifications'
    | '/officer-visits'
    | '/profile'
    | '/recalls'
    | '/register'
    | '/regulatory-alerts'
    | '/regulatory-radar'
    | '/sample-tracker'
    | '/scheme-selector'
    | '/vault'
    | '/admin/documents'
    | '/admin/retrieval-quality'
    | '/payments/$applicationId'
    | '/registration/new'
    | '/standards/$standardKey'
    | '/verify/certificate'
    | '/admin'
    | '/renewals'
    | '/standards'
    | '/renewals/$applicationId/wizard'
    | '/renewals/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/appeals'
    | '/business-account'
    | '/calendar'
    | '/certificates'
    | '/chat'
    | '/classification'
    | '/compliance-chain'
    | '/conformity'
    | '/dashboard'
    | '/developers'
    | '/document-corrections'
    | '/document-cortex'
    | '/factory-audits'
    | '/grievance'
    | '/intel-feed'
    | '/invoices'
    | '/jurisdiction'
    | '/knowledge-nexus'
    | '/laboratory-matcher'
    | '/legal'
    | '/license-actions'
    | '/locations'
    | '/notifications'
    | '/officer-visits'
    | '/profile'
    | '/recalls'
    | '/register'
    | '/regulatory-alerts'
    | '/regulatory-radar'
    | '/renewals'
    | '/sample-tracker'
    | '/scheme-selector'
    | '/standards'
    | '/vault'
    | '/admin/documents'
    | '/admin/retrieval-quality'
    | '/payments/$applicationId'
    | '/registration/new'
    | '/standards_/$standardKey'
    | '/verify/certificate'
    | '/admin/'
    | '/renewals/'
    | '/standards/'
    | '/renewals/$applicationId/wizard'
    | '/renewals/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealsRoute: typeof AppealsRoute
  BusinessAccountRoute: typeof BusinessAccountRoute
  CalendarRoute: typeof CalendarRoute
  CertificatesRoute: typeof CertificatesRoute
  ChatRoute: typeof ChatRoute
  ClassificationRoute: typeof ClassificationRoute
  ComplianceChainRoute: typeof ComplianceChainRoute
  ConformityRoute: typeof ConformityRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  DocumentCorrectionsRoute: typeof DocumentCorrectionsRoute
  DocumentCortexRoute: typeof DocumentCortexRoute
  FactoryAuditsRoute: typeof FactoryAuditsRoute
  GrievanceRoute: typeof GrievanceRoute
  IntelFeedRoute: typeof IntelFeedRoute
  InvoicesRoute: typeof InvoicesRoute
  JurisdictionRoute: typeof JurisdictionRoute
  KnowledgeNexusRoute: typeof KnowledgeNexusRoute
  LaboratoryMatcherRoute: typeof LaboratoryMatcherRoute
  LegalRoute: typeof LegalRoute
  LicenseActionsRoute: typeof LicenseActionsRoute
  LocationsRoute: typeof LocationsRoute
  NotificationsRoute: typeof NotificationsRoute
  OfficerVisitsRoute: typeof OfficerVisitsRoute
  ProfileRoute: typeof ProfileRoute
  RecallsRoute: typeof RecallsRoute
  RegisterRoute: typeof RegisterRoute
  RegulatoryAlertsRoute: typeof RegulatoryAlertsRoute
  RegulatoryRadarRoute: typeof RegulatoryRadarRoute
  RenewalsRoute: typeof RenewalsRouteWithChildren
  SampleTrackerRoute: typeof SampleTrackerRoute
  SchemeSelectorRoute: typeof SchemeSelectorRoute
  StandardsRoute: typeof StandardsRouteWithChildren
  VaultRoute: typeof VaultRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminRetrievalQualityRoute: typeof AdminRetrievalQualityRoute
  PaymentsApplicationIdRoute: typeof PaymentsApplicationIdRoute
  RegistrationNewRoute: typeof RegistrationNewRoute
  StandardsStandardKeyRoute: typeof StandardsStandardKeyRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-account': {
      id: '/business-account'
      path: '/business-account'
      fullPath: '/business-account'
      preLoaderRoute: typeof BusinessAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification': {
      id: '/classification'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof ClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-chain': {
      id: '/compliance-chain'
      path: '/compliance-chain'
      fullPath: '/compliance-chain'
      preLoaderRoute: typeof ComplianceChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformity': {
      id: '/conformity'
      path: '/conformity'
      fullPath: '/conformity'
      preLoaderRoute: typeof ConformityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-corrections': {
      id: '/document-corrections'
      path: '/document-corrections'
      fullPath: '/document-corrections'
      preLoaderRoute: typeof DocumentCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-cortex': {
      id: '/document-cortex'
      path: '/document-cortex'
      fullPath: '/document-cortex'
      preLoaderRoute: typeof DocumentCortexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory-audits': {
      id: '/factory-audits'
      path: '/factory-audits'
      fullPath: '/factory-audits'
      preLoaderRoute: typeof FactoryAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-feed': {
      id: '/intel-feed'
      path: '/intel-feed'
      fullPath: '/intel-feed'
      preLoaderRoute: typeof IntelFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurisdiction': {
      id: '/jurisdiction'
      path: '/jurisdiction'
      fullPath: '/jurisdiction'
      preLoaderRoute: typeof JurisdictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-nexus': {
      id: '/knowledge-nexus'
      path: '/knowledge-nexus'
      fullPath: '/knowledge-nexus'
      preLoaderRoute: typeof KnowledgeNexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory-matcher': {
      id: '/laboratory-matcher'
      path: '/laboratory-matcher'
      fullPath: '/laboratory-matcher'
      preLoaderRoute: typeof LaboratoryMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license-actions': {
      id: '/license-actions'
      path: '/license-actions'
      fullPath: '/license-actions'
      preLoaderRoute: typeof LicenseActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer-visits': {
      id: '/officer-visits'
      path: '/officer-visits'
      fullPath: '/officer-visits'
      preLoaderRoute: typeof OfficerVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recalls': {
      id: '/recalls'
      path: '/recalls'
      fullPath: '/recalls'
      preLoaderRoute: typeof RecallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-alerts': {
      id: '/regulatory-alerts'
      path: '/regulatory-alerts'
      fullPath: '/regulatory-alerts'
      preLoaderRoute: typeof RegulatoryAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-radar': {
      id: '/regulatory-radar'
      path: '/regulatory-radar'
      fullPath: '/regulatory-radar'
      preLoaderRoute: typeof RegulatoryRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-tracker': {
      id: '/sample-tracker'
      path: '/sample-tracker'
      fullPath: '/sample-tracker'
      preLoaderRoute: typeof SampleTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheme-selector': {
      id: '/scheme-selector'
      path: '/scheme-selector'
      fullPath: '/scheme-selector'
      preLoaderRoute: typeof SchemeSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retrieval-quality': {
      id: '/admin/retrieval-quality'
      path: '/admin/retrieval-quality'
      fullPath: '/admin/retrieval-quality'
      preLoaderRoute: typeof AdminRetrievalQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$applicationId': {
      id: '/payments/$applicationId'
      path: '/payments/$applicationId'
      fullPath: '/payments/$applicationId'
      preLoaderRoute: typeof PaymentsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/new': {
      id: '/registration/new'
      path: '/registration/new'
      fullPath: '/registration/new'
      preLoaderRoute: typeof RegistrationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals/': {
      id: '/renewals/'
      path: '/'
      fullPath: '/renewals/'
      preLoaderRoute: typeof RenewalsIndexRouteImport
      parentRoute: typeof RenewalsRoute
    }
    '/standards/': {
      id: '/standards/'
      path: '/'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof StandardsRoute
    }
    '/standards_/$standardKey': {
      id: '/standards_/$standardKey'
      path: '/standards/$standardKey'
      fullPath: '/standards/$standardKey'
      preLoaderRoute: typeof StandardsStandardKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/certificate': {
      id: '/verify/certificate'
      path: '/verify/certificate'
      fullPath: '/verify/certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals/$applicationId/': {
      id: '/renewals/$applicationId/'
      path: '/$applicationId'
      fullPath: '/renewals/$applicationId/'
      preLoaderRoute: typeof RenewalsApplicationIdIndexRouteImport
      parentRoute: typeof RenewalsRoute
    }
    '/renewals/$applicationId/wizard': {
      id: '/renewals/$applicationId/wizard'
      path: '/$applicationId/wizard'
      fullPath: '/renewals/$applicationId/wizard'
      preLoaderRoute: typeof RenewalsApplicationIdWizardRouteImport
      parentRoute: typeof RenewalsRoute
    }
  }
}

interface RenewalsRouteChildren {
  RenewalsIndexRoute: typeof RenewalsIndexRoute
  RenewalsApplicationIdWizardRoute: typeof RenewalsApplicationIdWizardRoute
  RenewalsApplicationIdIndexRoute: typeof RenewalsApplicationIdIndexRoute
}

const RenewalsRouteChildren: RenewalsRouteChildren = {
  RenewalsIndexRoute: RenewalsIndexRoute,
  RenewalsApplicationIdWizardRoute: RenewalsApplicationIdWizardRoute,
  RenewalsApplicationIdIndexRoute: RenewalsApplicationIdIndexRoute,
}

const RenewalsRouteWithChildren = RenewalsRoute._addFileChildren(
  RenewalsRouteChildren,
)

interface StandardsRouteChildren {
  StandardsIndexRoute: typeof StandardsIndexRoute
}

const StandardsRouteChildren: StandardsRouteChildren = {
  StandardsIndexRoute: StandardsIndexRoute,
}

const StandardsRouteWithChildren = StandardsRoute._addFileChildren(
  StandardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealsRoute: AppealsRoute,
  BusinessAccountRoute: BusinessAccountRoute,
  CalendarRoute: CalendarRoute,
  CertificatesRoute: CertificatesRoute,
  ChatRoute: ChatRoute,
  ClassificationRoute: ClassificationRoute,
  ComplianceChainRoute: ComplianceChainRoute,
  ConformityRoute: ConformityRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  DocumentCorrectionsRoute: DocumentCorrectionsRoute,
  DocumentCortexRoute: DocumentCortexRoute,
  FactoryAuditsRoute: FactoryAuditsRoute,
  GrievanceRoute: GrievanceRoute,
  IntelFeedRoute: IntelFeedRoute,
  InvoicesRoute: InvoicesRoute,
  JurisdictionRoute: JurisdictionRoute,
  KnowledgeNexusRoute: KnowledgeNexusRoute,
  LaboratoryMatcherRoute: LaboratoryMatcherRoute,
  LegalRoute: LegalRoute,
  LicenseActionsRoute: LicenseActionsRoute,
  LocationsRoute: LocationsRoute,
  NotificationsRoute: NotificationsRoute,
  OfficerVisitsRoute: OfficerVisitsRoute,
  ProfileRoute: ProfileRoute,
  RecallsRoute: RecallsRoute,
  RegisterRoute: RegisterRoute,
  RegulatoryAlertsRoute: RegulatoryAlertsRoute,
  RegulatoryRadarRoute: RegulatoryRadarRoute,
  RenewalsRoute: RenewalsRouteWithChildren,
  SampleTrackerRoute: SampleTrackerRoute,
  SchemeSelectorRoute: SchemeSelectorRoute,
  StandardsRoute: StandardsRouteWithChildren,
  VaultRoute: VaultRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminRetrievalQualityRoute: AdminRetrievalQualityRoute,
  PaymentsApplicationIdRoute: PaymentsApplicationIdRoute,
  RegistrationNewRoute: RegistrationNewRoute,
  StandardsStandardKeyRoute: StandardsStandardKeyRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
