import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { Paperclip, Send, X } from "lucide-react";
import { useTranslation } from "react-i18next";

import { AmbientBackground } from "@/components/ambient-background";
import { Chat3DBackground } from "@/components/chat-3d-background";
import { AppSidebar } from "@/components/app-sidebar";
import { BrandMark } from "@/components/brand-mark";
import { ChatBubble } from "@/components/chat-bubble";
import { LanguageToggle } from "@/components/language-toggle";
import { MobileSidebar } from "@/components/mobile-sidebar";
import { NotificationBell } from "@/components/notification-bell";
import { ProductClassificationWizard } from "@/components/product-classification-wizard";
import { ThemeToggle } from "@/components/theme-toggle";
import { ThinkingIndicator } from "@/components/thinking-indicator";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { getMockBotReply, getMockReplyForCategory } from "@/lib/mock-bot";
import { ChatApi, ExperienceApi } from "@/lib/api-client";
import { useSoundEffects } from "@/hooks/use-sound-effects";
import { useUserProfile } from "@/hooks/use-user-profile";
import type { ChatMessage, MessageFeedback } from "@/lib/types";

const MOCK_REPLY_DELAY_MS = 500;
const HIGHLIGHT_DURATION_MS = 1500;

// A sent user question is real free text (nothing to re-translate it with),
// but a mock bot reply is demo content — store which canned reply it is and
// resolve its text/citations from the current language on every render, so
// it tracks the language toggle just like the seeded conversation does.
type SentEntry =
  | { kind: "user"; text: string }
  | { kind: "mockReply"; replyIndex: number }
  | { kind: "categoryReply"; categoryKey: string }
  | { kind: "liveReply"; text: string; citations?: ChatMessage["citations"]; status?: "declined" };

// A queued message is either a free-typed question (round-robin mock reply)
// or one generated by the classification wizard, which carries the chosen
// category so its reply matches that category's seed standard instead.
interface QueuedMessage {
  text: string;
  categoryKey?: string;
}

function App() {
  const { t, i18n } = useTranslation(["chat", "conversation"]);

  const seedMessages = t("conversation:seedMessages", {
    returnObjects: true,
  }) as ChatMessage[];
  const [sentEntries, setSentEntries] = useState<SentEntry[]>([]);
  const sentMessages: ChatMessage[] = sentEntries.map((entry) => {
    if (entry.kind === "user") return { sender: "user", text: entry.text };
    if (entry.kind === "liveReply") {
      return {
        sender: "bot",
        text: entry.text,
        citations: entry.citations,
        status: entry.status,
      };
    }
    if (entry.kind === "categoryReply") {
      return {
        sender: "bot",
        ...getMockReplyForCategory(entry.categoryKey, i18n.language),
      };
    }
    return getMockBotReply(entry.replyIndex, i18n.language);
  });
  const [isConversationCleared, setIsConversationCleared] = useState(false);
  const messages = [
    ...(isConversationCleared ? [] : seedMessages),
    ...sentMessages,
  ];
  // Only surface seed questions whose seeded answer is actually a confident,
  // cited one — suggesting a question the demo itself declines would be a
  // bad first impression of what SAATHI can do.
  const suggestedQuestions = seedMessages
    .map((msg, i) => ({ msg, next: seedMessages[i + 1] }))
    .filter(
      ({ msg, next }) =>
        msg.sender === "user" && next?.sender === "bot" && !next.status,
    )
    .map(({ msg }) => msg.text)
    .slice(0, 3);
  const prefersReducedMotion = useReducedMotion();

  const [input, setInput] = useState("");
  const [attachedFileName, setAttachedFileName] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [highlightedIndex, setHighlightedIndex] = useState<number | null>(null);
  // D7 — feedback keyed by the same `message-${index}` id used for
  // scroll/highlight, so it can later be joined with analytics data.
  const [feedbackByMessageId, setFeedbackByMessageId] = useState<
    Record<string, MessageFeedback>
  >({});
  const contentRef = useRef<HTMLDivElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);
  const mockReplyCountRef = useRef(0);
  const highlightTimeoutRef = useRef<number | undefined>(undefined);
  const pendingReplyTimeoutRef = useRef<number | undefined>(undefined);

  // While a bot reply is still being typed out, any further sent messages
  // wait in queueRef (isProcessingRef guards it) rather than being shown
  // immediately, so the conversation stays in strict alternating order.
  const queueRef = useRef<QueuedMessage[]>([]);
  const isProcessingRef = useRef(false);
  const [isAwaitingReply, setIsAwaitingReply] = useState(false);
  const {
    profile: userProfile,
    setProfile: setUserProfile,
    soundEnabled,
    setSoundEnabled,
  } = useUserProfile();
  const { playSendSound, playClearSound } = useSoundEffects(soundEnabled);

  const pendingReplyMessageIndex =
    isAwaitingReply &&
    sentEntries.length > 0 &&
    sentEntries[sentEntries.length - 1].kind !== "user"
      ? (isConversationCleared ? 0 : seedMessages.length) +
        sentEntries.length -
        1
      : null;

  // The reply hasn't been appended to sentEntries yet (still inside the
  // MOCK_REPLY_DELAY_MS timeout) — show a placeholder bubble until it lands
  // and its own typing animation takes over.
  const isThinking =
    isAwaitingReply &&
    (sentEntries.length === 0 ||
      sentEntries[sentEntries.length - 1].kind === "user");

  useEffect(() => {
    const content = contentRef.current;
    if (!content) return;

    const observer = new ResizeObserver(() => {
      bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
    });
    observer.observe(content);

    return () => observer.disconnect();
  }, []);

  function handleSelectHistory(index: number) {
    document.getElementById(`message-${index}`)?.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });

    window.clearTimeout(highlightTimeoutRef.current);
    setHighlightedIndex(index);
    highlightTimeoutRef.current = window.setTimeout(() => {
      setHighlightedIndex(null);
    }, HIGHLIGHT_DURATION_MS);
  }

  // Shows the next queued message (if any) and schedules its reply, unless
  // a reply is already in flight — handleReplyRevealed() calls this again
  // once that reply finishes typing, advancing the queue one turn at a time.
  // Dispatches question to the real SAATHI AI Compliance & RAG engine
  function processNext() {
    if (isProcessingRef.current) return;
    const next = queueRef.current.shift();
    if (next === undefined) return;

    isProcessingRef.current = true;
    playSendSound();
    setIsAwaitingReply(true);
    setSentEntries((prev) => [...prev, { kind: "user", text: next.text }]);

    ChatApi.askQuestion(next.text, i18n.language)
      .then((aiRes) => {
        setSentEntries((prev) => [
          ...prev,
          {
            kind: "liveReply",
            text: aiRes.reply,
            citations: aiRes.citations,
            status: aiRes.status,
          },
        ]);
      })
      .catch((err) => {
        console.warn("Backend chat error, falling back to statutory response:", err);
        const replyEntry: SentEntry = next.categoryKey
          ? { kind: "categoryReply", categoryKey: next.categoryKey }
          : { kind: "mockReply", replyIndex: mockReplyCountRef.current++ };
        setSentEntries((prev) => [...prev, replyEntry]);
      });
  }

  function handleReplyRevealed() {
    isProcessingRef.current = false;
    setIsAwaitingReply(false);
    processNext();
  }

  function handleClearChat() {
    playClearSound();
    window.clearTimeout(pendingReplyTimeoutRef.current);
    window.clearTimeout(highlightTimeoutRef.current);
    queueRef.current = [];
    isProcessingRef.current = false;
    setIsAwaitingReply(false);
    setSentEntries([]);
    setFeedbackByMessageId({});
    setHighlightedIndex(null);
    setIsConversationCleared(true);
  }

  function handleSend() {
    if (input.trim() === "" && !attachedFileName) return;
    const attachmentSuffix = attachedFileName
      ? ` [Image attached: ${attachedFileName}]`
      : "";
    queueRef.current.push({
      text: `${input.trim()}${attachmentSuffix}`.trim(),
    });
    setInput("");
    setAttachedFileName(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
    processNext();
  }

  function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith("image/")) return;
    setAttachedFileName(file.name);
  }

  function handleWizardSubmit(question: string, categoryKey: string) {
    queueRef.current.push({ text: question, categoryKey });
    processNext();
  }

  function handleFeedbackChange(
    messageId: string,
    feedback: MessageFeedback | undefined,
  ) {
    setFeedbackByMessageId((prev) => {
      if (feedback === undefined) {
        const next = { ...prev };
        delete next[messageId];
        return next;
      }
      return { ...prev, [messageId]: feedback };
    });

    if (feedback) {
      const msgIndex = parseInt(messageId.replace("message-", ""), 10);
      const targetMsg = messages[msgIndex];
      ExperienceApi.submitFeedback({
        sessionId: "active_chat_session",
        query: messages[0]?.text || "User inquiry",
        answer: targetMsg?.text || "Answer",
        vote: feedback.vote,
        comment: feedback.comment,
      }).catch((err) => {
        console.warn("Could not persist feedback to backend:", err);
      });
    }
  }

  // Authentication is now gated centrally by ProtectedRoute (see
  // routes/chat.tsx), not here — App itself no longer needs to know
  // whether anyone is signed in.
  return (
    <div className="relative h-dvh w-full overflow-hidden bg-background">
      <AmbientBackground />
      <Chat3DBackground />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 overflow-hidden"
      >
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_120%_65%_at_50%_-10%,var(--accent),transparent_60%),radial-gradient(ellipse_90%_50%_at_100%_100%,var(--muted),transparent_55%)] opacity-70" />
        <div className="absolute -left-32 top-24 size-[28rem] rounded-full bg-[#c6d8e2]/18 blur-3xl" />
        <div className="absolute bottom-[-10rem] right-[18%] size-[34rem] rounded-full bg-[#d9c6a3]/16 blur-3xl" />
        <div className="absolute inset-0 opacity-[0.15] [background-image:radial-gradient(rgba(12,50,86,0.22)_0.7px,transparent_0.7px)] [background-size:24px_24px]" />
      </div>
      <div className="relative z-10 flex h-full w-full">
        <AppSidebar
          messages={messages}
          onSelect={handleSelectHistory}
          onClear={handleClearChat}
          profile={userProfile}
          soundEnabled={soundEnabled}
          onProfileChange={setUserProfile}
          onSoundEnabledChange={setSoundEnabled}
        />

        <div className="flex min-w-0 flex-1 justify-center px-0 sm:px-4">
          <div className="flex h-full w-full max-w-2xl flex-col">
            <header className="flex items-center gap-2 border-b border-[var(--card)]/60 bg-[var(--card)]/25 px-4 py-3 shadow-[0_8px_20px_rgba(44,53,59,0.04)] backdrop-blur-xl sm:px-6">
              <MobileSidebar
                messages={messages}
                onSelect={handleSelectHistory}
                onClear={handleClearChat}
                profile={userProfile}
                soundEnabled={soundEnabled}
                onProfileChange={setUserProfile}
                onSoundEnabledChange={setSoundEnabled}
              />
              <div className="flex items-center gap-2">
                <BrandMark size="sm" className="md:hidden" />
                <span className="font-semibold tracking-tight text-primary md:hidden">
                  {t("chat:logo")}
                </span>
              </div>
              <div className="ml-auto flex items-center gap-2">
                <LanguageToggle />
                <ThemeToggle variant="ghost" size="icon" />
                <NotificationBell />
              </div>
            </header>

            <ScrollArea className="min-w-0 flex-1 min-h-0">
              <div
                ref={contentRef}
                className="flex min-w-0 flex-col gap-3 p-4 sm:p-6"
              >
                {messages.length === 0 && !isThinking && (
                  <motion.div
                    initial={
                      prefersReducedMotion ? false : { opacity: 0, y: 10 }
                    }
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    className="flex min-h-[22rem] flex-col items-center justify-center px-6 py-12 text-center"
                  >
                    <BrandMark
                      size="sm"
                      className="mb-4 rounded-xl shadow-[inset_0_1px_0_var(--border),0_10px_18px_rgba(12,50,86,0.14)]"
                    />
                    <h1 className="font-serif text-2xl font-semibold tracking-tight text-primary">
                      {t("chat:clearChat.emptyTitle")}
                    </h1>
                    <p className="mt-2 max-w-xs text-sm leading-relaxed text-muted-foreground">
                      {t("chat:clearChat.emptyDescription")}
                    </p>
                    {suggestedQuestions.length > 0 && (
                      <div className="mt-5 flex max-w-sm flex-wrap items-center justify-center gap-2">
                        {suggestedQuestions.map((question) => (
                          <button
                            key={question}
                            type="button"
                            onClick={() => setInput(question)}
                            className="elevation-1 elevation-lift rounded-full border border-border bg-card px-3.5 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-muted"
                          >
                            {question}
                          </button>
                        ))}
                      </div>
                    )}
                  </motion.div>
                )}
                {messages.map((msg, index) => (
                  <ChatBubble
                    key={index}
                    id={`message-${index}`}
                    message={msg}
                    highlighted={index === highlightedIndex}
                    onRevealComplete={
                      index === pendingReplyMessageIndex
                        ? handleReplyRevealed
                        : undefined
                    }
                    feedback={feedbackByMessageId[`message-${index}`]}
                    onFeedbackChange={(feedback) =>
                      handleFeedbackChange(`message-${index}`, feedback)
                    }
                  />
                ))}
                <AnimatePresence>
                  {isThinking && <ThinkingIndicator />}
                </AnimatePresence>
                <div ref={bottomRef} />
              </div>
            </ScrollArea>

            <div className="flex flex-col gap-2 border-t border-[var(--card)]/60 bg-[var(--card)]/25 p-3 shadow-[0_-8px_20px_rgba(44,53,59,0.04)] backdrop-blur-xl sm:p-4">
              <ProductClassificationWizard onSubmit={handleWizardSubmit} />
              <AnimatePresence>
                {attachedFileName && (
                  <motion.div
                    initial={
                      prefersReducedMotion ? false : { opacity: 0, scale: 0.92 }
                    }
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.92 }}
                    transition={{ duration: 0.2 }}
                    className="flex items-center gap-2 self-start rounded-xl border border-primary/20 bg-primary/8 px-3 py-1.5 font-mono text-[0.62rem] text-primary"
                  >
                    <Paperclip className="size-3.5" aria-hidden />
                    <span className="max-w-[220px] truncate">
                      {attachedFileName}
                    </span>
                    <button
                      type="button"
                      onClick={() => {
                        setAttachedFileName(null);
                        if (fileInputRef.current)
                          fileInputRef.current.value = "";
                      }}
                      className="rounded-full p-0.5 transition-colors hover:bg-primary/10"
                      aria-label="Remove attached image"
                    >
                      <X className="size-3" aria-hidden />
                    </button>
                  </motion.div>
                )}
              </AnimatePresence>
              <div className="flex items-center gap-2">
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={handleFileChange}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => fileInputRef.current?.click()}
                  className="size-10 shrink-0 rounded-xl border-[var(--card)]/70 bg-[var(--card)]/35 text-muted-foreground shadow-[inset_0_1px_0_var(--border)] transition-transform duration-200 hover:-translate-y-0.5 hover:bg-[var(--card)]/60"
                  aria-label="Attach an image"
                >
                  <Paperclip className="size-4" aria-hidden />
                </Button>
                <Input
                  type="text"
                  placeholder={t("chat:inputPlaceholder")}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      handleSend();
                    }
                  }}
                  className="h-10 transition-shadow duration-200 focus-visible:shadow-[0_0_0_4px_color-mix(in_oklch,var(--primary)_14%,transparent)]"
                />
                <Button
                  onClick={handleSend}
                  size="icon"
                  disabled={input.trim() === "" && !attachedFileName}
                  className="group size-10 shrink-0 transition-transform duration-200 enabled:hover:-translate-y-0.5 disabled:opacity-50"
                  aria-label={t("chat:sendAriaLabel")}
                >
                  <Send className="transition-transform duration-200 group-enabled:group-hover:translate-x-0.5 group-enabled:group-hover:-translate-y-0.5" />
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
