/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClassificationRouteImport } from './routes/classification'
import { Route as ConformityRouteImport } from './routes/conformity'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocumentCortexRouteImport } from './routes/document-cortex'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as IntelFeedRouteImport } from './routes/intel-feed'
import { Route as JurisdictionRouteImport } from './routes/jurisdiction'
import { Route as KnowledgeNexusRouteImport } from './routes/knowledge-nexus'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegulatoryRadarRouteImport } from './routes/regulatory-radar'
import { Route as SampleTrackerRouteImport } from './routes/sample-tracker'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as PaymentsApplicationIdRouteImport } from './routes/payments.$applicationId'
import { Route as RenewalsIndexRouteImport } from './routes/renewals.index'
import { Route as RenewalsApplicationIdRouteImport } from './routes/renewals.$applicationId'
import { Route as StandardsIndexRouteImport } from './routes/standards.index'
import { Route as StandardsStandardKeyRouteImport } from './routes/standards_.$standardKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationRoute = ClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformityRoute = ConformityRouteImport.update({
  id: '/conformity',
  path: '/conformity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentCortexRoute = DocumentCortexRouteImport.update({
  id: '/document-cortex',
  path: '/document-cortex',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelFeedRoute = IntelFeedRouteImport.update({
  id: '/intel-feed',
  path: '/intel-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const JurisdictionRoute = JurisdictionRouteImport.update({
  id: '/jurisdiction',
  path: '/jurisdiction',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeNexusRoute = KnowledgeNexusRouteImport.update({
  id: '/knowledge-nexus',
  path: '/knowledge-nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryRadarRoute = RegulatoryRadarRouteImport.update({
  id: '/regulatory-radar',
  path: '/regulatory-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleTrackerRoute = SampleTrackerRouteImport.update({
  id: '/sample-tracker',
  path: '/sample-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsApplicationIdRoute = PaymentsApplicationIdRouteImport.update({
  id: '/payments/$applicationId',
  path: '/payments/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsIndexRoute = RenewalsIndexRouteImport.update({
  id: '/renewals/',
  path: '/renewals/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsApplicationIdRoute = RenewalsApplicationIdRouteImport.update({
  id: '/renewals/$applicationId',
  path: '/renewals/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/standards/',
  path: '/standards/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsStandardKeyRoute = StandardsStandardKeyRouteImport.update({
  id: '/standards_/$standardKey',
  path: '/standards/$standardKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/classification': typeof ClassificationRoute
  '/conformity': typeof ConformityRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/document-cortex': typeof DocumentCortexRoute
  '/grievance': typeof GrievanceRoute
  '/intel-feed': typeof IntelFeedRoute
  '/jurisdiction': typeof JurisdictionRoute
  '/knowledge-nexus': typeof KnowledgeNexusRoute
  '/legal': typeof LegalRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/regulatory-radar': typeof RegulatoryRadarRoute
  '/sample-tracker': typeof SampleTrackerRoute
  '/vault': typeof VaultRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/payments/$applicationId': typeof PaymentsApplicationIdRoute
  '/renewals/$applicationId': typeof RenewalsApplicationIdRoute
  '/standards/$standardKey': typeof StandardsStandardKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/renewals/': typeof RenewalsIndexRoute
  '/standards/': typeof StandardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/classification': typeof ClassificationRoute
  '/conformity': typeof ConformityRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/document-cortex': typeof DocumentCortexRoute
  '/grievance': typeof GrievanceRoute
  '/intel-feed': typeof IntelFeedRoute
  '/jurisdiction': typeof JurisdictionRoute
  '/knowledge-nexus': typeof KnowledgeNexusRoute
  '/legal': typeof LegalRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/regulatory-radar': typeof RegulatoryRadarRoute
  '/sample-tracker': typeof SampleTrackerRoute
  '/vault': typeof VaultRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/payments/$applicationId': typeof PaymentsApplicationIdRoute
  '/renewals/$applicationId': typeof RenewalsApplicationIdRoute
  '/standards/$standardKey': typeof StandardsStandardKeyRoute
  '/admin': typeof AdminIndexRoute
  '/renewals': typeof RenewalsIndexRoute
  '/standards': typeof StandardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/classification': typeof ClassificationRoute
  '/conformity': typeof ConformityRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/document-cortex': typeof DocumentCortexRoute
  '/grievance': typeof GrievanceRoute
  '/intel-feed': typeof IntelFeedRoute
  '/jurisdiction': typeof JurisdictionRoute
  '/knowledge-nexus': typeof KnowledgeNexusRoute
  '/legal': typeof LegalRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/regulatory-radar': typeof RegulatoryRadarRoute
  '/sample-tracker': typeof SampleTrackerRoute
  '/vault': typeof VaultRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/payments/$applicationId': typeof PaymentsApplicationIdRoute
  '/renewals/$applicationId': typeof RenewalsApplicationIdRoute
  '/standards_/$standardKey': typeof StandardsStandardKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/renewals/': typeof RenewalsIndexRoute
  '/standards/': typeof StandardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/classification'
    | '/conformity'
    | '/dashboard'
    | '/developers'
    | '/document-cortex'
    | '/grievance'
    | '/intel-feed'
    | '/jurisdiction'
    | '/knowledge-nexus'
    | '/legal'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/regulatory-radar'
    | '/sample-tracker'
    | '/vault'
    | '/admin/documents'
    | '/payments/$applicationId'
    | '/renewals/$applicationId'
    | '/standards/$standardKey'
    | '/admin/'
    | '/renewals/'
    | '/standards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/classification'
    | '/conformity'
    | '/dashboard'
    | '/developers'
    | '/document-cortex'
    | '/grievance'
    | '/intel-feed'
    | '/jurisdiction'
    | '/knowledge-nexus'
    | '/legal'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/regulatory-radar'
    | '/sample-tracker'
    | '/vault'
    | '/admin/documents'
    | '/payments/$applicationId'
    | '/renewals/$applicationId'
    | '/standards/$standardKey'
    | '/admin'
    | '/renewals'
    | '/standards'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/classification'
    | '/conformity'
    | '/dashboard'
    | '/developers'
    | '/document-cortex'
    | '/grievance'
    | '/intel-feed'
    | '/jurisdiction'
    | '/knowledge-nexus'
    | '/legal'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/regulatory-radar'
    | '/sample-tracker'
    | '/vault'
    | '/admin/documents'
    | '/payments/$applicationId'
    | '/renewals/$applicationId'
    | '/standards_/$standardKey'
    | '/admin/'
    | '/renewals/'
    | '/standards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ClassificationRoute: typeof ClassificationRoute
  ConformityRoute: typeof ConformityRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  DocumentCortexRoute: typeof DocumentCortexRoute
  GrievanceRoute: typeof GrievanceRoute
  IntelFeedRoute: typeof IntelFeedRoute
  JurisdictionRoute: typeof JurisdictionRoute
  KnowledgeNexusRoute: typeof KnowledgeNexusRoute
  LegalRoute: typeof LegalRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegulatoryRadarRoute: typeof RegulatoryRadarRoute
  SampleTrackerRoute: typeof SampleTrackerRoute
  VaultRoute: typeof VaultRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  PaymentsApplicationIdRoute: typeof PaymentsApplicationIdRoute
  RenewalsApplicationIdRoute: typeof RenewalsApplicationIdRoute
  StandardsStandardKeyRoute: typeof StandardsStandardKeyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RenewalsIndexRoute: typeof RenewalsIndexRoute
  StandardsIndexRoute: typeof StandardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification': {
      id: '/classification'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof ClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformity': {
      id: '/conformity'
      path: '/conformity'
      fullPath: '/conformity'
      preLoaderRoute: typeof ConformityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-cortex': {
      id: '/document-cortex'
      path: '/document-cortex'
      fullPath: '/document-cortex'
      preLoaderRoute: typeof DocumentCortexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel-feed': {
      id: '/intel-feed'
      path: '/intel-feed'
      fullPath: '/intel-feed'
      preLoaderRoute: typeof IntelFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurisdiction': {
      id: '/jurisdiction'
      path: '/jurisdiction'
      fullPath: '/jurisdiction'
      preLoaderRoute: typeof JurisdictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-nexus': {
      id: '/knowledge-nexus'
      path: '/knowledge-nexus'
      fullPath: '/knowledge-nexus'
      preLoaderRoute: typeof KnowledgeNexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-radar': {
      id: '/regulatory-radar'
      path: '/regulatory-radar'
      fullPath: '/regulatory-radar'
      preLoaderRoute: typeof RegulatoryRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-tracker': {
      id: '/sample-tracker'
      path: '/sample-tracker'
      fullPath: '/sample-tracker'
      preLoaderRoute: typeof SampleTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$applicationId': {
      id: '/payments/$applicationId'
      path: '/payments/$applicationId'
      fullPath: '/payments/$applicationId'
      preLoaderRoute: typeof PaymentsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals/': {
      id: '/renewals/'
      path: '/renewals'
      fullPath: '/renewals/'
      preLoaderRoute: typeof RenewalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals/$applicationId': {
      id: '/renewals/$applicationId'
      path: '/renewals/$applicationId'
      fullPath: '/renewals/$applicationId'
      preLoaderRoute: typeof RenewalsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/': {
      id: '/standards/'
      path: '/standards'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards_/$standardKey': {
      id: '/standards_/$standardKey'
      path: '/standards/$standardKey'
      fullPath: '/standards/$standardKey'
      preLoaderRoute: typeof StandardsStandardKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ClassificationRoute: ClassificationRoute,
  ConformityRoute: ConformityRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  DocumentCortexRoute: DocumentCortexRoute,
  GrievanceRoute: GrievanceRoute,
  IntelFeedRoute: IntelFeedRoute,
  JurisdictionRoute: JurisdictionRoute,
  KnowledgeNexusRoute: KnowledgeNexusRoute,
  LegalRoute: LegalRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegulatoryRadarRoute: RegulatoryRadarRoute,
  SampleTrackerRoute: SampleTrackerRoute,
  VaultRoute: VaultRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  PaymentsApplicationIdRoute: PaymentsApplicationIdRoute,
  RenewalsApplicationIdRoute: RenewalsApplicationIdRoute,
  StandardsStandardKeyRoute: StandardsStandardKeyRoute,
  AdminIndexRoute: AdminIndexRoute,
  RenewalsIndexRoute: RenewalsIndexRoute,
  StandardsIndexRoute: StandardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
