export interface ShowcaseLanguage {
  code: string;
  nativeName: string;
  englishName: string;
  greeting: string;
  script: string;
  prompt: string;
  sampleQuery: string;
  standardClause: string;
  dir?: "ltr" | "rtl";
}

export const SHOWCASE_LANGUAGES: ShowcaseLanguage[] = [
  {
    code: "hi",
    nativeName: "हिन्दी",
    englishName: "Hindi",
    greeting: "नमस्ते",
    script: "Devanagari",
    prompt: "हिंदी में पूछें",
    sampleQuery: "क्या यह टू-व्हीलर हेलमेट IS 4151:2015 मानक के अनुसार प्रमाणित है?",
    standardClause: "IS 4151:2015 • खंड 4.2 (संरचनात्मक सुरक्षा)",
  },
  {
    code: "en",
    nativeName: "English",
    englishName: "English",
    greeting: "Welcome",
    script: "Latin",
    prompt: "Ask in English",
    sampleQuery: "Is this protective helmet compliant with IS 4151:2015 specifications?",
    standardClause: "IS 4151:2015 • Clause 4.2 (Impact Attenuation)",
  },
  {
    code: "bn",
    nativeName: "বাংলা",
    englishName: "Bengali",
    greeting: "স্বাগতম",
    script: "Bengali",
    prompt: "বাংলায় জিজ্ঞাসা করুন",
    sampleQuery: "এই হেলমেটটি কি ভারতীয় মানক IS 4151:2015 অনুযায়ী প্রত্যয়িত?",
    standardClause: "IS 4151:2015 • অনুচ্ছেদ ৪.২ (আঘাত সুরক্ষা)",
  },
  {
    code: "mr",
    nativeName: "मराठी",
    englishName: "Marathi",
    greeting: "नमस्कार",
    script: "Devanagari",
    prompt: "मराठीत विचारा",
    sampleQuery: "हे दुचाकी हेल्मेट भारतीय मानक IS 4151:2015 नुसार प्रमाणित आहे का?",
    standardClause: "IS 4151:2015 • कलम ४.२ (आघात संरक्षण)",
  },
  {
    code: "te",
    nativeName: "తెలుగు",
    englishName: "Telugu",
    greeting: "నమస్కారం",
    script: "Telugu",
    prompt: "తెలుగులో అడగండి",
    sampleQuery: "ఈ ద్విచక్ర వాహన హెల్మెట్ IS 4151:2015 ప్రమాణాల ప్రకారం ధృవీకరించబడిందా?",
    standardClause: "IS 4151:2015 • క్లాజ్ 4.2 (రక్షణ ప్రమాణాలు)",
  },
  {
    code: "ta",
    nativeName: "தமிழ்",
    englishName: "Tamil",
    greeting: "வணக்கம்",
    script: "Tamil",
    prompt: "தமிழில் கேளுங்கள்",
    sampleQuery: "இந்த இருசக்கர வாகன தலைக்கவசம் IS 4151:2015 தரநிலைக்கு இணங்குகிறதா?",
    standardClause: "IS 4151:2015 • பிரிவு 4.2 (பாதுகாப்பு தரநிலை)",
  },
  {
    code: "gu",
    nativeName: "ગુજરાતી",
    englishName: "Gujarati",
    greeting: "નમસ્તે",
    script: "Gujarati",
    prompt: "ગુજરાતીમાં પૂછો",
    sampleQuery: "શું આ ટુ-વ્હીલર હેલ્મેટ IS 4151:2015 ધોરણ મુજબ પ્રમાણિત છે?",
    standardClause: "IS 4151:2015 • કલમ 4.2 (ઈમ્પેક્ટ પ્રોટેક્શન)",
  },
  {
    code: "ur",
    nativeName: "اردو",
    englishName: "Urdu",
    greeting: "خوش آمدید",
    script: "Perso-Arabic",
    dir: "rtl",
    prompt: "اردو میں پوچھیں",
    sampleQuery: "کیا یہ دو پہیہ ہیلمٹ IS 4151:2015 معیار کے مطابق تصدیق شدہ ہے؟",
    standardClause: "IS 4151:2015 • شق 4.2 (حفاظتی معیار)",
  },
  {
    code: "kn",
    nativeName: "ಕನ್ನಡ",
    englishName: "Kannada",
    greeting: "ನಮಸ್ಕಾರ",
    script: "Kannada",
    prompt: "ಕನ್ನಡದಲ್ಲಿ ಕೇಳಿ",
    sampleQuery: "ಈ ದ್ವಿಚಕ್ರ ವಾಹನ ಹೆಲ್ಮೆಟ್ IS 4151:2015 ಗುಣಮಟ್ಟದಂತೆ ಪ್ರಮಾಣೀಕರಿಸಲಾಗಿದೆಯೇ?",
    standardClause: "IS 4151:2015 • ಷರತ್ತು 4.2 (ಘರ್ಷಣೆ ತಡೆಗಟ್ಟುವಿಕೆ)",
  },
  {
    code: "or",
    nativeName: "ଓଡ଼ିଆ",
    englishName: "Odia",
    greeting: "ନମସ୍କାର",
    script: "Odia",
    prompt: "ଓଡ଼ିଆରେ ପଚାରନ୍ତୁ",
    sampleQuery: "ଏହି ହେଲମେଟ୍ ଭାରତୀୟ ମାନକ IS 4151:2015 ଅନୁଯାୟୀ ପ୍ରମାଣିତ କି?",
    standardClause: "IS 4151:2015 • ଧାରା ୪.୨ (ସୁରକ୍ଷା ମାନଦଣ୍ଡ)",
  },
  {
    code: "ml",
    nativeName: "മലയാളം",
    englishName: "Malayalam",
    greeting: "നമസ്കാരം",
    script: "Malayalam",
    prompt: "മലയാളത്തിൽ ചോദിക്കുക",
    sampleQuery: "ഈ ഇരുചക്ര വാഹന ഹെൽമെറ്റ് IS 4151:2015 മാനദണ്ഡം പാലിക്കുന്നുണ്ടോ?",
    standardClause: "IS 4151:2015 • വകുപ്പ് 4.2 (സുരക്ഷാ മാനദണ്ഡം)",
  },
  {
    code: "pa",
    nativeName: "ਪੰਜਾਬੀ",
    englishName: "Punjabi",
    greeting: "ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ",
    script: "Gurmukhi",
    prompt: "ਪੰਜਾਬੀ ਵਿੱਚ ਪੁੱਛੋ",
    sampleQuery: "ਕੀ ਇਹ ਦੋ-ਪਹੀਆ ਹੈਲਮੇਟ IS 4151:2015 ਮਿਆਰ ਅਨੁਸਾਰ ਪ੍ਰਮਾਣਿਤ ਹੈ?",
    standardClause: "IS 4151:2015 • ਧਾਰਾ 4.2 (ਸੁਰੱਖਿਆ ਨਿਯਮ)",
  },
  {
    code: "as",
    nativeName: "অসমীয়া",
    englishName: "Assamese",
    greeting: "নমস্কাৰ",
    script: "Bengali-Assamese",
    prompt: "অসমীয়াত সোধক",
    sampleQuery: "এই দুচকীয়া হেলমেটটো IS 4151:2015 মান অনুসৰি প্ৰমাণিত নেকি?",
    standardClause: "IS 4151:2015 • দফা ৪.২ (সুৰক্ষা নীতি)",
  },
  {
    code: "mai",
    nativeName: "मैथिली",
    englishName: "Maithili",
    greeting: "प्रणाम",
    script: "Devanagari",
    prompt: "मैथिलीमे पुछू",
    sampleQuery: "की ई दुपहिया हेलमेट IS 4151:2015 मानकक अनुसार प्रमाणित अछि?",
    standardClause: "IS 4151:2015 • खंड 4.2 (संरचनात्मक सुरक्षा)",
  },
  {
    code: "sat",
    nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",
    englishName: "Santali",
    greeting: "ᱡᱚᱦᱟᱨ",
    script: "Ol Chiki",
    prompt: "ᱥᱟᱱᱛᱟᱲᱤ ᱛᱮ ᱠᱩᱞᱤ ᱢᱮ",
    sampleQuery: "ᱪᱮᱫ ᱱᱚᱣᱟ ᱦᱮᱞᱢᱮᱴ IS 4151:2015 ᱢᱟᱱᱚᱠ ᱞᱮᱠᱟᱛᱮ ᱯᱨᱚᱢᱟᱱᱤᱛ ᱠᱟᱱᱟ?",
    standardClause: "IS 4151:2015 • ᱫᱷᱟᱨᱟ 4.2 (ᱨᱩᱠᱷᱤᱭᱟᱹ ᱢᱟᱱᱚᱠ)",
  },
  {
    code: "ks",
    nativeName: "کٲشُر",
    englishName: "Kashmiri",
    greeting: "آداب",
    script: "Perso-Arabic",
    dir: "rtl",
    prompt: "کأشِرِس مَنٛز پٕرِچھِو",
    sampleQuery: "کیا یہٕ ٹُو ویٖلر ہؠلمَٹ چھا IS 4151:2015 مِیارَس مُطٲبِق تَصدیٖق شُدٕ؟",
    standardClause: "IS 4151:2015 • شق 4.2 (حفاظتی معیار)",
  },
  {
    code: "ne",
    nativeName: "नेपाली",
    englishName: "Nepali",
    greeting: "नमस्ते",
    script: "Devanagari",
    prompt: "नेपालीमा सोध्नुहोस्",
    sampleQuery: "के यो दुई पाङ्ग्रे हेलमेट IS 4151:2015 मापदण्ड अनुसार प्रमाणित छ?",
    standardClause: "IS 4151:2015 • दफा ४.२ (सुरक्षा मापदण्ड)",
  },
  {
    code: "doi",
    nativeName: "डोगरी",
    englishName: "Dogri",
    greeting: "नमस्ते",
    script: "Devanagari",
    prompt: "डोगरी च पुच्छो",
    sampleQuery: "केह् एह् दुपहिया हेलमेट IS 4151:2015 मानक दे मताबक प्रमाणित ऐ?",
    standardClause: "IS 4151:2015 • खंड 4.2 (सुरक्षा मानक)",
  },
  {
    code: "kok",
    nativeName: "कोंकणी",
    englishName: "Konkani",
    greeting: "नमस्कार",
    script: "Devanagari",
    prompt: "कोंकणींत विचारात",
    sampleQuery: "हें दोन चाकी हेल्मेट IS 4151:2015 मानका प्रमाण प्रमाणित आसा काय?",
    standardClause: "IS 4151:2015 • कलम ४.२ (सुरक्षा नेम)",
  },
  {
    code: "mni",
    nativeName: "ꯃꯩꯇꯩ ꯂꯣꯟ",
    englishName: "Manipuri",
    greeting: "ꯈꯨꯔꯨꯝꯖꯔꯤ",
    script: "Meitei",
    prompt: "ꯃৈতৈলোন্দা হংবিয়ু",
    sampleQuery: "হিলমেট অসি IS 4151:2015 ষ্টেন্দার্দকী মতুং ইন্না সেক্শন তৌবব্রা?",
    standardClause: "IS 4151:2015 • క్లాజ్ 4.2 (ঙাকশেল মান)",
  },
  {
    code: "brx",
    nativeName: "बोडो",
    englishName: "Bodo",
    greeting: "खुल्लुमबाय",
    script: "Devanagari",
    prompt: "बर'आव सों",
    sampleQuery: "बे नै-साखाया हेलमेटआ IS 4151:2015 मानगोनां बादियै रोखा जाबाय नामा?",
    standardClause: "IS 4151:2015 • दफा 4.2 (रैखाथि नेम)",
  },
  {
    code: "sa",
    nativeName: "संस्कृतम्",
    englishName: "Sanskrit",
    greeting: "नमस्ते",
    script: "Devanagari",
    prompt: "संस्कृते पृच्छतु",
    sampleQuery: "किम् इदं द्विचक्रिका-शिरस्त्राणं IS 4151:2015 मानकानुसारं प्रमाणितम् अस्ति?",
    standardClause: "IS 4151:2015 • खण्डः ४.२ (संरक्षणात्मकमानकम्)",
  },
];
